version: 2
updates:
  # Keep dependencies up to date using npm
  - package-ecosystem: npm
    directory: /
    # Check for updates at 2am UTC
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: daily
