sequenceDiagram
    title NASA Text Notifer
    
    participant CRON
    participant Lambday
    participant DB
    participant S3
    participant NASA_API
    participant Twilio
    
    CRON->>Lambday: Trigger Periodically
    Lambday->>DB: check metadata table for blob id
    alt APOD does not exist
        Lambday->>NASA_API: get APOD
        NASA_API->>Lambday: return APOD
        Lambday->>S3: store APOD
        Lambday->>DB: write metadata table w/ blob id
    else APOD exists
        S3->>Lambday: grab cached photo
    end
    DB->>Lambday: Get list of users for period
    Lambday->>Twilio: Batched send sms to users (?)