AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: development
        NODE_OPTIONS: --enable-source-maps
  Api:
    Cors:
      AllowMethods: "'POST, OPTIONS'"
      AllowHeaders: "'Content-Type, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, X-Requested-With, cf-turnstile-response, HX-Request, HX-Target, HX-Current-URL, HX-Trigger, HX-Trigger-Name, HX-Boosted, HX-History-Restore-Request'"
      AllowOrigin: "'*'"

Resources:
  SignupProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: backend/functions/signup-processor/Dockerfile
      DockerContext: .
      DockerTag: signup-processor
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["index.handler"]
      Architectures:
        - arm64
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        SignupAPI:
          Type: Api
          Properties:
            Path: /signup
            Method: post

Outputs:
  SignupApi:
    Description: "API Gateway endpoint URL for Signup function"
    Value: !Sub "http://127.0.0.1:3000/signup"
