AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  signup-processor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SignupProcessor:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/signup-processor
      Handler: index.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Events:
        SignupProcessor:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /signup
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        Target: "es2020"
        Sourcemap: true
        SourceContent: false
        EntryPoints:
          - index.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SignupProcessorApi:
    Description: API Gateway endpoint URL for Prod stage for Signup Processor function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/signup/
  SignupProcessorFunction:
    Description: Signup Processor Lambda Function ARN
    Value: !GetAtt SignupProcessorFunction.Arn
  SignupProcessorFunctionIamRole:
    Description: Implicit IAM Role created for Signup Processor function
    Value: !GetAtt SignupProcessorFunctionRole.Arn
