AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseUrl:
    Type: String
    Description: URL for the database connection
    NoEcho: true
  # TwilioAccountSid:
  #   Type: String
  #   Description: Twilio Account SID
  #   NoEcho: true
  # TwilioAuthToken:
  #   Type: String
  #   Description: Twilio Auth Token
  #   NoEcho: true
  # TwilioSenderPhoneNumber:
  #   Type: String
  #   Description: Twilio Sender Phone Number
  #   NoEcho: true

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: development
        NODE_OPTIONS: --enable-source-maps
  Api:
    Cors:
      AllowMethods: "'POST, OPTIONS'"
      AllowHeaders: "'Content-Type, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, X-Requested-With, cf-turnstile-response, HX-Request, HX-Target, HX-Current-URL, HX-Trigger, HX-Trigger-Name, HX-Boosted, HX-History-Restore-Request'"
      AllowOrigin: "'*'"

Resources:
  SignupProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: backend/functions/signup-processor/Dockerfile
      DockerContext: .
      DockerTag: signup-processor
      DockerBuildArgs:
        FUNCTION_NAME: "signup-processor"
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["index.handler"]
      Architectures:
        - arm64
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        SignupAPI:
          Type: Api
          Properties:
            Path: /signup
            Method: post

  # MessageSenderFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: backend/functions/message-sender/
  #     Handler: dist/index.handler # Output from build.js is dist/index.js, main export is handler
  #     Runtime: nodejs22.x # Based on earlier SAM build logs for this function
  #     Architectures:
  #       - arm64
  #     Environment:
  #       Variables:
  #         DATABASE_URL: !Ref DatabaseUrl
  #         # DATABASE_URL_TEST is handled by process.env in code if needed locally via .env.json
  #         TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
  #         TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
  #         TWILIO_SENDER_PHONE_NUMBER: !Ref TwilioSenderPhoneNumber
  #         NODE_OPTIONS: --enable-source-maps # From Globals, but good to be explicit if needed
  #         NODE_ENV: development # From Globals
  #     Events:
  #       HourlySchedule:
  #         Type: Schedule
  #         Properties:
  #           Schedule: "rate(1 hour)" # Runs every hour
  #           Name: HourlyMessageSend
  #           Description: Sends text message notifications based on user preferences
  #     MemorySize: 512 # Optional: Adjust as needed
  #     Timeout: 60 # Optional: Adjust as needed, default is 30 from Globals
  #   Metadata:
  #     BuildMethod: nodejs22.x # SAM will use the Node.js build process

Outputs:
  SignupApi:
    Description: "API Gateway endpoint URL for Signup function"
    Value: !Sub "http://127.0.0.1:3000/signup"
