[tool.ruff]

[tool.ruff.lint]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["backend", "frontend", "shared"]

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["*_test.py"]
markers = [
    "integration: marks tests as integration tests",
] 