#!/bin/sh

# Run linting and formatting
npm run lint-staged
lint_status=$?

if [ $lint_status -ne 0 ]; then
  echo "Lint-staged failed! Please fix the errors and try committing again."
  exit $lint_status
fi

# Run Typechecking
npm run type-check
type_check_status=$?

if [ $type_check_status -ne 0 ]; then
  echo "Typechecking failed! Please fix the errors and try committing again."
  exit $type_check_status
fi

# Run unit tests
npm run test:unit
test_status=$?

if [ $test_status -ne 0 ]; then
  echo "Unit tests failed! Please fix the errors and try committing again."
  exit $test_status
fi

# Ensure the script exits with success if everything passed
exit 0
