name: Daily Automated Integration Tests

on:
  schedule:
    # Run every day at 1:00 AM UTC
    - cron: "0 1 * * *"

  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-test-and-package:
    runs-on: ubuntu-24.04-arm
    env:
      DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      APOD_IMAGE_BUCKET_NAME: ${{ secrets.APOD_IMAGE_BUCKET_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npm install --no-save @biomejs/cli-linux-arm64

      - name: Build shared package
        run: npm run build --workspace=shared

      - name: Run linting
        run: npm run lint

      - name: Run general type checking
        run: npm run type-check

      - name: Run frontend Astro check
        run: npm run astro-check --workspace=frontend

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration

      - name: Build frontend (test only)
        run: npm run build --workspace=frontend
