name: Deploy Website

on:
  # Run on push to main
  push:
    branches:
      - main

  # Allow manual triggering
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Parallel validation and testing jobs - no dependencies
  lint:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.2.4
      - name: Run Biome
        run: biome ci .

  type-check:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci
      - name: Run general type checking
        run: npm run check:ts

  terraform-validation:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Read Terraform version
        id: tf_version
        run: echo "version=$(printf '%s' "$(cat .terraform-version)")" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ steps.tf_version.outputs.version }}-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-${{ steps.tf_version.outputs.version }}-

      - name: Run Terraform Validation
        run: npm run check:iac

  test:
    runs-on: ubuntu-24.04-arm
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
      PUBLIC_SIGNUP_API_URL: ${{ secrets.PUBLIC_SIGNUP_API_URL }}
      PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.PUBLIC_TURNSTILE_SITE_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY_URLS: ${{ secrets.ECR_REPOSITORY_URLS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

  build-and-package:
    runs-on: ubuntu-24.04-arm
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
      PUBLIC_SIGNUP_API_URL: ${{ secrets.PUBLIC_SIGNUP_API_URL }}
      PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.PUBLIC_TURNSTILE_SITE_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY_URLS: ${{ secrets.ECR_REPOSITORY_URLS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      # Build shared package first (required by frontend)
      - name: Build shared package
        run: npm run build:shared:ci

      # Build frontend (depends on shared)
      - name: Build frontend
        run: npm run build:frontend

      - name: Verify build artifacts exist
        run: |
          echo "Checking shared/dist/ contents:"
          ls -la shared/dist/ || echo "shared/dist/ does not exist"
          echo "Checking frontend/dist/ contents:"
          ls -la frontend/dist/ || echo "frontend/dist/ does not exist"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: |
            shared/dist/
            frontend/dist/
          retention-days: 1

  deploy-lambdas:
    needs: [lint, type-check, terraform-validation, test, build-and-package]
    runs-on: ubuntu-24.04-arm
    env:
      ECR_REPOSITORY_URLS: ${{ secrets.ECR_REPOSITORY_URLS }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # AWS and ECR Setup
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::730335616323:role/GitHubActionsDeploymentRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-artifacts-${{ github.run_id }}
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install lambda dependencies
        run: npm ci --workspace=backend --include-workspace-root=false --no-save

      # Build and Deploy Lambda Containers
      - name: Build and push Lambda containers
        working-directory: backend/functions
        run: ./build.sh

  deploy-frontend:
    needs: [lint, type-check, terraform-validation, test, build-and-package]
    runs-on: ubuntu-24.04-arm
    env:
      STATIC_WEBSITE_BUCKET: ${{ secrets.STATIC_WEBSITE_BUCKET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::730335616323:role/GitHubActionsDeploymentRole
          aws-region: us-east-1

      # Frontend Download Build Artifact And Deploy
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-artifacts-${{ github.run_id }}
          path: .
      - name: Deploy to S3
        run: cd frontend/dist && aws s3 sync --delete ./ s3://${{ secrets.STATIC_WEBSITE_BUCKET }}
