name: No Deploy

on:
  # Run on all pull requests
  pull_request:

jobs:
  build-test-and-package:
    runs-on: ubuntu-24.04-arm
    env:
      DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AWS_REGION: "us-east-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: |
          npm install

      - name: Build all packages
        run: npm run build

      - name: Run linting
        run: npm run lint

      - name: Run general type checking
        run: npm run type-check

      - name: Run frontend Astro check
        run: npm run astro-check

      - name: Run unit tests
        run: npm run test:unit
