name: No Deploy (Test and Build)

on:
  # Run on any push to any branch except master
  push:
    branches-ignore: [main]

  # Run on any pull request targeting master
  pull_request:
    branches: [main]

jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    strategy:
      matrix:
        node-version: [22]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Lint
      run: pnpm run lint
    - name: Deep Type check
      run: pnpm run type-check
    - name: Build application
      run: pnpm run build
    - name: Deploy to S3
      run: aws s3 sync --delete ./dist/ s3://${{ secrets.STATIC_WEBSITE_BUCKET }}
    - name: Build Lambda Functions
      run: |
        cd lambda/notifications
        chmod +x build.sh
        ./build.sh
    - name: Deploy Lambda Functions to S3
      run: |
        cd lambda/notifications
        for dir in */; do
          if [ -f "${dir}deployment.zip" ]; then
            function_name=$(basename "$dir")
            echo "Deploying $function_name..."
            aws s3 cp "${dir}deployment.zip" "s3://${{ secrets.LAMBDA_BUCKET_ID }}/${function_name}/deployment.zip"
          fi
        done
    
